TARGET_NAME := deevee

SOURCES_C := \
	src/libretro.c \
	src/deevee_core.c \
	src/deevee_content.c \
	src/deevee_decoder.c \
	src/deevee_disc.c \
	src/deevee_dvd.c \
	src/deevee_iso.c \
	src/deevee_nav.c \
	src/deevee_video.c \
	src/deevee_audio.c

INCFLAGS := -Iinclude -Isrc
WARNFLAGS := -Wall -Wextra -Wpedantic
CSTD := -std=c99

CFLAGS += $(CSTD) $(WARNFLAGS) $(INCFLAGS)

ifeq ($(HAVE_FFMPEG),1)
	FFMPEG_LIBS ?= -lavcodec -lavutil -lswscale
	CFLAGS += -DHAVE_FFMPEG=1 $(FFMPEG_CFLAGS)
	LDFLAGS += $(FFMPEG_LIBS)
endif
